# Generated by Django 4.0.6 on 2022-07-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=8),
            preserve_default=False,
        ),
    ]
